### ISSUE TITLE
Why do I get an error when I change the batch size?

### ISSUE THREAD

**Issue by Jasonx0123** [hhqweasd/LG-ShadowNet#5]
When I changed the batch_size=2, I got the error like that:
![微信图片_20240706110221](https://github.com/hhqweasd/LG-ShadowNet/assets/46207106/9e58988a-9072-4a4f-acf8-76e1a96986de)

**Comment by Jasonx0123** [comment]
I don't know how to solve this problem, can you give me some help?

**Comment by hhqweasd** [comment]
Hi @Jasonshao0123,

It seems like you're encountering a shape mismatch error when changing the batch size. This often happens when the feature dimensions are not compatible with the new batch size. To resolve this issue, you'll need to adjust the dimensions of the corresponding tensors or layers accordingly.
